export const TYPES = {
  SIGNUP_CURRENT_USER: 'SIGNUP_CURRENT_USER',
  CREATE_SIGNUP_ERROR: 'CREATE_SIGNUP_ERROR',
  LOGIN_CURRENT_USER: 'LOGIN_CURRENT_USER',
  CREATE_LOGIN_ERROR: 'CREATE_LOGIN_ERROR',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER',
  CREATE_LOGOUT_ERROR: 'CREATE_LOGOUT_ERROR',
  GET_PROJECTS: 'GET_PROJECTS',
  PROJECT_LOADING: 'PROJECT_LOADING',
};
